### ISSUE TITLE
附件上传

### ISSUE THREAD

**Issue by wangyong159357** [lifengdi/spring-cloud-gateway-demo#1]
我用您这个打印日志的方法之后，发现附件无法进行上传了。。大神，请赐教

**Comment by lifengdi** [comment]
问题基本定位到了，你可以拉一下最新的代码看看是否解决。

**Comment by wangyong159357** [comment]
谢谢您，我也找到什么问题了，是那个校验是否上传文件的问题，因为我们的请求自己定义了请求头，所以在验证是否附件上传的时候失败了，走的表单提交，因此附件上传失败了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lifengdi"<notifications@github.com&gt;; 
发送时间: 2020年7月9日(星期四) 下午5:01
收件人: "lifengdi/spring-cloud-gateway-demo"<spring-cloud-gateway-demo@noreply.github.com&gt;; 
抄送: "追求卓越"<739455347@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lifengdi/spring-cloud-gateway-demo] 附件上传 (#1)





 
问题基本定位到了，你可以拉一下最新的代码看看是否解决。
